"""
Agent 7 — Pipeline Orchestrator
Coordinates all agents, manages state, streams progress via WebSocket.
"""
import asyncio
import logging
import uuid
from datetime import datetime
from typing import Optional, Callable
from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession

from agents.scout import DEFAULT_CITIES
from agents.enrichment import EnrichmentAgent
from agents.signal_analyst import SignalAnalyst
from agents.scoring_engine import ScoringEngine
from agents.ranking_engine import RankingEngine
from agents.dossier_generator import DossierGenerator
from agents.content_enrichment import ContentEnrichmentAgent
from agents.council import CouncilAgent
from agents.council_gate import qualifies_for_council
from models import Company, PipelineRun, Dossier, Memo
from database import AsyncSessionLocal
from config import settings

logger = logging.getLogger(__name__)


def _format_council_thesis_markdown(thesis: dict) -> str:
    """Format council thesis dict as readable markdown for the memo viewer."""
    consensus_colors = {
        "strong buy": "🟢",
        "moderate interest": "🟡",
        "split": "🟠",
        "pass": "🔴",
    }
    icon = consensus_colors.get(thesis.get("council_consensus", ""), "⚖️")
    strengths = "\n".join(f"- {s}" for s in thesis.get("key_strengths", []))
    risks = "\n".join(f"- {r}" for r in thesis.get("key_risks", []))

    return f"""# Council Investment Thesis
{icon} **Council Consensus:** {thesis.get('council_consensus', 'N/A').title()}

## Investment Thesis
{thesis.get('investment_thesis', '')}

## Key Strengths
{strengths or '- Analysis in progress'}

## Key Risks
{risks or '- Standard HVAC sector risks apply'}

## Valuation Estimate
{thesis.get('valuation_estimate', 'See valuation tab for proxy estimate')}

## Recommended Action
**{thesis.get('recommended_action', 'Monitor')}**

---
*Generated by LLM Council — 3-model deliberation (Stage 1: independent analysis, Stage 2: peer review, Stage 3: chairman synthesis)*
"""


class PipelineOrchestrator:
    def __init__(self, ws_broadcast: Optional[Callable] = None):
        self.ws_broadcast = ws_broadcast
        self.current_run_id: Optional[str] = None
        self.is_running = False

    async def _broadcast(self, stage: str, message: str, progress: float = 0.0, extra: dict = None):
        if self.ws_broadcast:
            try:
                await self.ws_broadcast({
                    "type": "progress",
                    "stage": stage,
                    "message": message,
                    "progress": round(min(progress, 1.0), 3),
                    **(extra or {}),
                })
            except Exception as e:
                logger.debug(f"WS broadcast failed: {e}")

    async def _save_run(self, run_id: str, **values):
        async with AsyncSessionLocal() as db:
            await db.execute(update(PipelineRun).where(PipelineRun.id == run_id).values(**values))
            await db.commit()

    async def run(
        self,
        cities: list[tuple[str, str]] = None,
        max_companies: int = 200,
        generate_dossiers_for_top: int = 20,
        run_id: str = None,
        user_id: str = None,
    ) -> str:
        if self.is_running:
            raise ValueError("A pipeline run is already in progress.")

        self.is_running = True
        run_id = run_id or str(uuid.uuid4())
        self.current_run_id = run_id

        async with AsyncSessionLocal() as db:
            pr = PipelineRun(
                id=run_id,
                status="running",
                config_json={"max_companies": max_companies},
                user_id=user_id,
                cities=cities,
            )
            db.add(pr)
            await db.commit()

        try:
            # ─── STAGE 1: Scout ─────────────────────────────────────────
            await self._broadcast("scout", "Discovering HVAC companies…", 0.0)
            all_cities = cities or DEFAULT_CITIES
            # Trim city list so max_per_city is always at least 8
            max_per_city = max(8, max_companies // max(len(all_cities), 1))
            num_cities = min(len(all_cities), max(1, max_companies // max_per_city + 1))
            target_cities = all_cities[:num_cities]

            if settings.firecrawl_api_key:
                from agents.firecrawl_scout import FirecrawlScout
                firecrawl_scout = FirecrawlScout(api_key=settings.firecrawl_api_key)
                companies_raw = await firecrawl_scout.run_batch(
                    target_cities,
                    max_per_city=max_per_city,
                )
                logger.info(f"FirecrawlScout discovered {len(companies_raw)} companies")
            else:
                # Free tier: OSMScout + YPScraper fallback for sparse cities
                from agents.osm_scout import OSMScout
                from agents.yp_scraper import YPScraper, OSM_FALLBACK_THRESHOLD

                osm_scout = OSMScout()
                yp_scraper = YPScraper()

                # OSM batch run
                companies_raw = await osm_scout.run_batch(
                    target_cities,
                    max_per_city=max_per_city,
                    progress_callback=lambda m, p: asyncio.create_task(
                        self._broadcast("scout", m, p * 0.18)
                    ),
                )

                # YP fallback: supplement any city where OSM found < threshold
                # (check per city by running YP for each if total is sparse)
                if len(companies_raw) < OSM_FALLBACK_THRESHOLD * len(target_cities):
                    logger.info(
                        f"OSM total {len(companies_raw)} is sparse — running YP fallback"
                    )
                    seen_place_ids = {c["place_id"] for c in companies_raw}
                    for city, state in target_cities:
                        yp_results = await yp_scraper.search_city(city, state, max_results=max_per_city)
                        for c in yp_results:
                            if c["place_id"] not in seen_place_ids:
                                seen_place_ids.add(c["place_id"])
                                companies_raw.append(c)

                logger.info(f"OSMScout+YP discovered {len(companies_raw)} companies")
            companies_raw = companies_raw[:max_companies]

            # Stamp user_id on all discovered companies
            if user_id:
                for c in companies_raw:
                    if isinstance(c, dict):
                        c["user_id"] = user_id

            total = len(companies_raw)
            logger.info(f"Scout complete: {total} companies")
            await self._broadcast("scout", f"Found {total} HVAC companies", 0.18)
            await self._save_run(run_id, current_stage="scout_complete", total_companies=total)

            # ─── Persist initial records ─────────────────────────────────
            async with AsyncSessionLocal() as db:
                for c in companies_raw:
                    res = await db.execute(
                        select(Company).where(Company.google_place_id == c.get("place_id"))
                    )
                    existing = res.scalar_one_or_none()
                    if existing:
                        c["id"] = existing.id
                        existing.name = c.get("name", existing.name)
                        existing.google_rating = c.get("google_rating")
                        existing.google_review_count = c.get("google_review_count")
                        existing.status = "scouted"
                    else:
                        cid = str(uuid.uuid4())
                        c["id"] = cid
                        db.add(Company(
                            id=cid,
                            name=c.get("name", ""),
                            address=c.get("address", ""),
                            city=c.get("city", ""),
                            state=c.get("state", ""),
                            phone=c.get("phone", ""),
                            website=c.get("website", ""),
                            google_place_id=c.get("place_id"),
                            google_rating=c.get("google_rating"),
                            google_review_count=c.get("google_review_count"),
                            category="HVAC",
                            status="scouted",
                            raw_google_data=c.get("raw_google_data"),
                            user_id=c.get("user_id"),
                        ))
                await db.commit()

            # ─── STAGE 2: Enrich ─────────────────────────────────────────
            await self._broadcast("enrich", "Enriching company data…", 0.18)
            enricher = EnrichmentAgent()
            try:
                companies_enriched = await enricher.enrich_batch(
                    companies_raw,
                    progress_callback=lambda m, p: self._broadcast("enrich", m, 0.18 + p * 0.22),
                )
            finally:
                await enricher.close()

            async with AsyncSessionLocal() as db:
                for c in companies_enriched:
                    await db.execute(
                        update(Company).where(Company.id == c.get("id")).values(
                            domain=c.get("domain"),
                            domain_age_years=c.get("domain_age_years"),
                            ssl_valid=c.get("ssl_valid"),
                            ssl_expiry=c.get("ssl_expiry"),
                            tech_stack=c.get("tech_stack", []),
                            website_active=c.get("website_active"),
                            website_load_time_ms=c.get("website_load_time_ms"),
                            website_last_checked=c.get("website_last_checked"),
                            has_facebook=c.get("has_facebook", False),
                            has_instagram=c.get("has_instagram", False),
                            website_outdated=c.get("website_outdated", False),
                            status="enriched",
                        )
                    )
                await db.commit()

            await self._broadcast("enrich", f"Enriched {len(companies_enriched)} companies", 0.40)

            # ─── STAGE 2.5: Content Enrichment ──────────────────────────
            await self._broadcast("content_enrich", "Extracting website content signals…", 0.40)
            if settings.firecrawl_api_key:
                content_agent = ContentEnrichmentAgent(api_key=settings.firecrawl_api_key)
                companies_after_content = await content_agent.enrich_batch(
                    companies_enriched,
                    progress_callback=lambda m, p: self._broadcast("content_enrich", m, 0.40 + p * 0.12),
                )
                await self._broadcast(
                    "content_enrich",
                    f"Content signals extracted for {len(companies_after_content)} companies",
                    0.50,
                )
            else:
                for c in companies_enriched:
                    c["content_enriched"] = False
                companies_after_content = companies_enriched
                logger.info("Content enrichment skipped — no FIRECRAWL_API_KEY")
                await self._broadcast("content_enrich", "Content enrichment skipped (no FIRECRAWL_API_KEY)", 0.50)

            async with AsyncSessionLocal() as db:
                for c in companies_after_content:
                    await db.execute(
                        update(Company).where(Company.id == c.get("id")).values(
                            is_family_owned_likely=c.get("is_family_owned_likely"),
                            offers_24_7=c.get("offers_24_7"),
                            service_count_estimated=c.get("service_count_estimated"),
                            years_in_business_claimed=c.get("years_in_business_claimed"),
                            is_recruiting=c.get("is_recruiting"),
                            technician_count_estimated=c.get("technician_count_estimated"),
                            serves_commercial=c.get("serves_commercial"),
                            content_enriched=c.get("content_enriched", False),
                        )
                    )
                await db.commit()

            await self._broadcast("content_enrich", f"Content stage complete ({len(companies_after_content)} companies)", 0.52)

            # ─── STAGE 3: Signal Analysis ────────────────────────────────
            await self._broadcast("signals", "Analyzing transition signals…", 0.52)
            analyst = SignalAnalyst()
            companies_signals = analyst.analyze_batch(companies_after_content)
            await self._broadcast("signals", "Signal analysis complete", 0.58)

            # ─── STAGE 4: Scoring ────────────────────────────────────────
            await self._broadcast("scoring", "Scoring acquisition probability…", 0.58)
            scorer = ScoringEngine()
            companies_scored = scorer.score_batch(companies_signals)
            await self._broadcast("scoring", "Scoring complete", 0.65)

            # ─── STAGE 5: Ranking ────────────────────────────────────────
            await self._broadcast("ranking", "Ranking candidates…", 0.65)
            ranker = RankingEngine()
            companies_ranked = ranker.rank(companies_scored)

            async with AsyncSessionLocal() as db:
                for c in companies_ranked:
                    await db.execute(
                        update(Company).where(Company.id == c.get("id")).values(
                            signals=c.get("signals", []),
                            score=c.get("score", 0),
                            conviction_score=c.get("conviction_score", 0),
                            score_breakdown=c.get("score_breakdown", {}),
                            transition_score=c.get("transition_score", 0),
                            quality_score=c.get("quality_score", 0),
                            platform_score=c.get("platform_score", 0),
                            score_explanation=c.get("score_explanation"),
                            rank=c.get("rank"),
                            status=c.get("status", "ranked"),
                        )
                    )
                await db.commit()

            await self._broadcast("ranking", f"Ranked {len(companies_ranked)} companies", 0.76)

            # ─── STAGE 7: Council Analysis ──────────────────────────────
            await self._broadcast("council", "Qualifying candidates for council review…", 0.76)

            if settings.openrouter_api_key:
                qualified = [
                    c for c in companies_ranked
                    if qualifies_for_council(c)
                ][:10]

                if qualified:
                    await self._broadcast(
                        "council",
                        f"LLM Council reviewing {len(qualified)} top candidates…",
                        0.77,
                    )
                    council_agent = CouncilAgent(api_key=settings.openrouter_api_key)
                    council_results = await council_agent.analyze_batch(
                        qualified,
                        progress_callback=lambda m, p: asyncio.create_task(
                            self._broadcast("council", m, 0.77 + p * 0.15)
                        ),
                    )

                    async with AsyncSessionLocal() as db:
                        for company_id, thesis in council_results:
                            content_md = _format_council_thesis_markdown(thesis)
                            existing = (await db.execute(
                                select(Memo).where(
                                    Memo.company_id == company_id,
                                    Memo.model_used == "council-v1",
                                )
                            )).scalar_one_or_none()
                            if existing:
                                existing.content = content_md
                                existing.updated_at = datetime.utcnow()
                            else:
                                db.add(Memo(
                                    company_id=company_id,
                                    version=2,
                                    title="Council Investment Thesis",
                                    content=content_md,
                                    status="final",
                                    model_used="council-v1",
                                    generated_at=datetime.utcnow(),
                                ))
                            await db.execute(
                                update(Company).where(Company.id == company_id).values(
                                    council_analyzed=True,
                                )
                            )
                        await db.commit()
                    await self._broadcast("council", f"Council analysis complete for {len(qualified)} companies", 0.92)
                else:
                    await self._broadcast("council", "No candidates qualified for council review (low scores or thin data)", 0.92)
            else:
                logger.info("Council stage skipped — no OPENROUTER_API_KEY")
                await self._broadcast("council", "Council stage skipped (configure OPENROUTER_API_KEY to enable)", 0.92)

            # ─── STAGE 8: Dossiers ───────────────────────────────────────
            top = [c for c in companies_ranked if c.get("status") == "top_candidate"]
            top = top[:generate_dossiers_for_top]
            await self._broadcast("dossiers", f"Writing dossiers for {len(top)} top targets…", 0.92)

            dossier_gen = DossierGenerator()
            dossier_results = await dossier_gen.generate_batch(
                top,
                progress_callback=lambda m, p: self._broadcast("dossiers", m, 0.92 + p * 0.05),
            )

            async with AsyncSessionLocal() as db:
                for company_id, content in dossier_results:
                    res = await db.execute(select(Dossier).where(Dossier.company_id == company_id))
                    existing_d = res.scalar_one_or_none()
                    if existing_d:
                        existing_d.content = content
                        existing_d.generated_at = datetime.utcnow()
                    else:
                        db.add(Dossier(
                            id=str(uuid.uuid4()),
                            company_id=company_id,
                            content=content,
                        ))
                    await db.execute(
                        update(Company).where(Company.id == company_id)
                        .values(status="dossier_generated")
                    )
                await db.commit()

            # ─── Finalize ────────────────────────────────────────────────
            await self._save_run(
                run_id,
                status="completed",
                current_stage="complete",
                total_companies=total,
                processed_companies=total,
                completed_at=datetime.utcnow(),
            )
            await self._broadcast(
                "complete",
                f"Pipeline complete — {len(top)} dossiers ready.",
                1.0,
                {"run_id": run_id},
            )
            if self.ws_broadcast:
                await self.ws_broadcast({"type": "complete", "run_id": run_id})

        except Exception as e:
            logger.exception(f"Pipeline run {run_id} failed: {e}")
            await self._save_run(
                run_id,
                status="failed",
                error=str(e),
                completed_at=datetime.utcnow(),
            )
            if self.ws_broadcast:
                await self.ws_broadcast({"type": "error", "message": str(e)})
        finally:
            self.is_running = False
            self.current_run_id = None

        return run_id
